#!/bin/bash
# vim: set ft=sh

set -e

exec 1>&2 # redirect all output to stderr for logging

payload=$TMPDIR/go-app-resource-request

package=$(jq -r '.source.package // ""' < $payload)
cmd=$(jq -r '.source.cmd // ""' < $payload)
out=$(jq -r '.source.out // ""' < $payload)
current_version=$(jq -r '.version.ref // ""' < $payload)

if [ -z "$package" ]; then
  echo "must specify package"
  exit 1
fi

if [ -z "$cmd" ]; then
  cmd="go install ."
fi

if [ -z "$out" ]; then
  binary=$(basename $package)
  out="$GOPATH/bin/$binary"
fi

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

mkdir -p $destination
cd $GOPATH/src/$package
git checkout $current_version

eval $cmd

cp $out $destination

jq -n '{
  version: { ref: $version },
  metadata: [
    { name: "ref", value: $version }
  ]
}' --arg version "$current_version" 
